version: '3'

services:

  db:
    image: mysql:8.0
    container_name: photography-db
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: photography_db
      MYSQL_TCP_PORT: 4001
    ports:
      - '4001:4001'
    volumes:
      - $PHOTO_APP_DIR/db/mysql_data:/var/lib/mysql

  frontend:
    build: ./frontend
    container_name: photography-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - ./app/node_modules
    stdin_open: true
    tty: true

  photo-api:
    depends_on: 
      - db
    image: eu.gcr.io/beironf/photo-api-docker
    container_name: photography-photo-api
    platform: linux/x86_64
    environment:
      DATABASE_HOST: db
    ports:
      - '3001:3001'

  image-api:
    depends_on:
      - db
    image: eu.gcr.io/beironf/image-api-docker
    container_name: photography-image-api
    platform: linux/x86_64
    environment:
      DATABASE_HOST: db
    ports:
      - '3002:3002'
    volumes:
      - $PHOTO_APP_DIR/storage/images:/opt/image-api/storage/images
      - $PHOTO_APP_DIR/storage/thumbnails:/opt/image-api/storage/thumbnails
      - $PHOTO_APP_DIR/storage/site-images:/opt/image-api/storage/site-images