version: '3'

services:

  photography-db:
    image: postgres:14
    container_name: photography-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '4001:5432'
    volumes:
      - $PHOTO_APP_DIR/photography-db/postgresql_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: photography-frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - ./app/node_modules
    stdin_open: true
    tty: true

  photo-api:
    depends_on:
      - photography-db
    image: eu.gcr.io/beironf/photo-api-docker
    container_name: photography-photo-api
    platform: linux/x86_64
    environment:
      DB_HOST: photography-db
    ports:
      - '3001:3001'

  image-api:
    depends_on:
      - photography-db
    image: eu.gcr.io/beironf/image-api-docker
    container_name: photography-image-api
    platform: linux/x86_64
    environment:
      DB_HOST: photography-db
    ports:
      - '3002:3002'
    volumes:
      - $PHOTO_APP_DIR/storage/images:/opt/image-api/storage/images
      - $PHOTO_APP_DIR/storage/thumbnails:/opt/image-api/storage/thumbnails
      - $PHOTO_APP_DIR/storage/site-images:/opt/image-api/storage/site-images
