version: "3"

services:
  photography-db:
    image: postgres:14
    container_name: photography-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPORT=4001
    ports:
      - "4001:4001"
    volumes:
      - $PHOTO_APP_DIR/photography-db/postgresql_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: photography-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - ./app/node_modules
    stdin_open: true
    tty: true

  api:
    depends_on:
      - photography-db
    image: beironf/photography-app/api
    container_name: photography-api
    platform: linux/x86_64
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://photography-db:4001/photography_db
    ports:
      - "3001:3001"
    volumes:
      - $PHOTO_APP_DIR/storage/images:/opt/api/storage/images
      - $PHOTO_APP_DIR/storage/thumbnails:/opt/api/storage/thumbnails
      - $PHOTO_APP_DIR/storage/site-images:/opt/api/storage/site-images
