apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-api
  labels:
    app: photo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photo-api
  template:
    metadata:
      labels:
        app: photo-api
    spec:
      containers:
        - name: photo-api
          image: photo-api-image
          ports:
            - name: photo-api-port
              containerPort: 3001
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Dconfig.resource=production.conf"
            - name: DB_USER
              value: photo-api
          livenessProbe:
            httpGet:
              path: /health-check
              port: photo-api-port
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health-check
              port: photo-api-port
            initialDelaySeconds: 20
            periodSeconds: 30
      serviceAccount: photo-api
