apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: photo-api-image
    newName: europe-west1-docker.pkg.dev/beiron-photography-app/docker-artifacts/photo-api
    newTag: latest
