apiVersion: v1
kind: Service
metadata:
  name: photo-api
  labels:
    app: photo-api
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: photo-api-port
  selector:
    app: photo-api
