apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-api
  labels:
    app: image-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-api
  template:
    metadata:
      labels:
        app: image-api
    spec:
      containers:
        - name: image-api
          image: image-api-image
          ports:
            - name: image-api-port
              containerPort: 3002
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Dconfig.resource=production.conf"
            - name: DB_USER
              value: image-api
          livenessProbe:
            httpGet:
              path: /health-check
              port: image-api-port
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health-check
              port: image-api-port
            initialDelaySeconds: 20
            periodSeconds: 30
      serviceAccount: image-api
