apiVersion: v1
kind: Service
metadata:
  name: image-api
  labels:
    app: image-api
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: image-api-port
  selector:
    app: image-api
